/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        // Deck radius scale
        'deck-xs':   'var(--radius-xs)',
        'deck-sm':   'var(--radius-sm)',
        'deck-md':   'var(--radius-md)',
        'deck-lg':   'var(--radius-lg)',
        'deck-xl':   'var(--radius-xl)',
        'deck-pill': 'var(--radius-pill)',
      },
      boxShadow: {
        'deck-sm':        'var(--shadow-sm)',
        'deck-md':        'var(--shadow-md)',
        'deck-lg':        'var(--shadow-lg)',
        'deck-glow-case': 'var(--shadow-glow-case)',
      },
      zIndex: {
        'deck-slide':     'var(--z-slide)',
        'deck-chrome':    'var(--z-chrome)',
        'deck-overview':  'var(--z-overview)',
        'deck-presenter': 'var(--z-presenter)',
        'deck-overlay':   'var(--z-overlay)',
        'deck-dialog':    'var(--z-dialog)',
        'deck-toast':     'var(--z-toast)',
      },
      spacing: {
        'deck-1':  'var(--space-1)',
        'deck-2':  'var(--space-2)',
        'deck-3':  'var(--space-3)',
        'deck-4':  'var(--space-4)',
        'deck-5':  'var(--space-5)',
        'deck-6':  'var(--space-6)',
        'deck-8':  'var(--space-8)',
        'deck-10': 'var(--space-10)',
        'deck-12': 'var(--space-12)',
        'deck-16': 'var(--space-16)',
      },
      colors: {
        // shadcn tokens
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },

        // ===== Deck v3.3 palette (raw hex via CSS vars) =====
        deck: {
          bg: 'var(--bg)',
          panel: 'var(--panel)',
          'panel-elevated': 'var(--panel-elevated)',
          cream: 'var(--cream)',
          'cream-muted': 'var(--cream-muted)',
          'cream-faint': 'var(--cream-faint)',
          'cream-dim': 'var(--cream-dim)',
          'cream-hairline': 'var(--cream-hairline)',
          'cream-ghost': 'var(--cream-ghost)',
          amber: 'var(--amber)',
          cyan: 'var(--cyan)',
          sage: 'var(--sage)',
          violet: 'var(--violet)',
          coral: 'var(--coral)',
          case: 'var(--case)',

          // Semantic status tokens (decoupled from case-study accents)
          success: 'var(--success)',
          warn: 'var(--warn)',
          danger: 'var(--danger)',
          info: 'var(--info)',

          // Legacy aliases — keep old components painting correctly
          surface: 'hsl(var(--deck-surface))',
          'surface-elevated': 'hsl(var(--deck-surface-elevated))',
          ink: 'var(--cream)',
          'ink-muted': 'var(--cream-muted)',
          'ink-subtle': 'var(--cream-faint)',
          rule: 'var(--cream-hairline)',
          'accent': 'var(--amber)',
          'accent-2': 'var(--coral)',
          signal: 'var(--sage)',
          warn: 'hsl(var(--deck-warn))',
          'data-1': 'var(--cyan)',
          'data-2': 'var(--violet)',
          'data-3': 'var(--sage)',
          'data-4': 'var(--coral)',
          'data-5': 'var(--amber)',
          'data-6': 'hsl(var(--deck-data-6))',
        },
      },
      fontFamily: {
        'deck-display': ['var(--font-display)'],
        'deck-body':    ['var(--font-body)'],
        'deck-mono':    ['var(--font-mono)'],
      },
      fontSize: {
        'deck-hero':       'var(--fs-hero)',
        'deck-hero-num':   'var(--fs-hero-num)',
        'deck-display':    'var(--fs-display)',
        'deck-bignum':     'var(--fs-bignum)',
        'deck-watermark':  'var(--fs-watermark)',
        'deck-h1':         'var(--fs-h1)',
        'deck-h1-lg':      'var(--fs-h1-lg)',
        'deck-h2':         'var(--fs-h2)',
        'deck-quote':      'var(--fs-quote)',
        'deck-h3':         'var(--fs-h3)',
        'deck-lead':       'var(--fs-lead)',
        'deck-kicker':     'var(--fs-kicker)',
        'deck-body-lg':    'var(--fs-body-lg)',
        'deck-body':       'var(--fs-body)',
        'deck-body-sm':    'var(--fs-body-sm)',
        'deck-meta':       'var(--fs-meta)',
        'deck-micro':      'var(--fs-micro)',
        'deck-nano':       'var(--fs-nano)',
      },
      letterSpacing: {
        'deck-display':    'var(--ls-display)',
        'deck-headline':   'var(--ls-headline)',
        'deck-mono-tight': 'var(--ls-mono-tight)',
        'deck-mono':       'var(--ls-mono)',
        'deck-mono-wide':  'var(--ls-mono-wide)',
      },
      transitionTimingFunction: {
        'deck-out':       'var(--ease-out)',
        'deck-overshoot': 'var(--ease-overshoot)',
        'deck-in-out':    'var(--deck-ease-in-out)',
        'deck-standard':  'var(--deck-ease-standard)',
      },
      transitionDuration: {
        'deck-fast':      '180ms',
        'deck-base':      '320ms',
        'deck-slow':      '640ms',
        'deck-narrative': '900ms',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up':   { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
}
